### ISSUE TITLE
Add a nightly build for `erlang/otp`'s main branch?

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [jelly-beam/otp-macos#1]
#### Is your feature request related to a problem?

No.

#### Describe the feature you'd like

We're only targeting tagged versions, at this moment. Should we have a special target for the main branch, too?

#### Describe alternatives you've considered

None.

#### Additional context

None.

**Comment by paulo-ferraz-oliveira** [comment]
This would also help understand if coming changes will break this repo's workflows.

**Comment by starbelly** [comment]
That makes sense to me.

**Comment by paulo-ferraz-oliveira** [comment]
Issue was auto-closed with linked pr that got closed because I rebased the main branch. We can at least, thus, track it's not yet done. 😄
